### ISSUE TITLE
Create accordion component

### ISSUE THREAD

**Issue by laurensgroeneveld** [bcc-code/bcc-design#156]
<img width="396" alt="image" src="https://github.com/bcc-code/bcc-design-library/assets/39056299/b68ee10e-e564-45a1-adca-e6dadf19a825">

<img width="413" alt="image" src="https://github.com/bcc-code/bcc-design-library/assets/39056299/acc18fa9-10af-4c9d-a1dd-3276e097e552">

## Acceptance criteria

- Add accordion component with neutral and brand variants
- The header is either text or a slot with custom content

## Design
https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=347-3437&mode=design

**Comment by lukaspoloki** [comment]
I can take it, currently implementing in Budget App
