### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by KajaKozuchBCC** [bcc-code/bcc-design#188]
Update icons: 
Current icon set are inconsistent, some of them include padding, some of them no. 

Acceptance criteria: 

- [x] upload icon from material google icon (24px) 
- [x] copy nested frame to specific icon component 

That will help us to achieve consistency of icon size with the code. 

Based on that issue we decided to: 
improve our icon approach. More on task #198

**Comment by u12206050** [comment]
In this regard icons have been updated to the slightly thicker 24px scale instead of the thinner 48px. #196
