### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Timvanderlaan** [bcc-code/bcc-design#223]
## User Story

As a ..., I want to ... so that ...

## Description

...

## Acceptance Criteria:

https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=395-6515&mode=design

**Comment by Lucas-Powell** [comment]
Bage

**Comment by laurensgroeneveld** [comment]
As far as I can see all the variants from the design have been implemented, is there a need for this issue? This is the case for some of the other issues as well, such as #222 (buttons)

**Comment by laurensgroeneveld** [comment]
Fully implemented already.
