### ISSUE TITLE
Stepper

### ISSUE THREAD

**Issue by Timvanderlaan** [bcc-code/bcc-design#224]
![image](https://github.com/bcc-code/bcc-design/assets/39056299/acc934d6-eee0-48bf-b3b8-6df1cdc15df8)

## Acceptance Criteria
- Each step has a text belonging to it
- The current step can be passed, which updates the step number, the step text, and the graphic below it with to show which step is selected

## Design
https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=3742-30106&mode=design

**Comment by lukaspoloki** [comment]
I cna try to implment it - I did already in budget and Donation, so it would be nice to finally implement it in the design library 😄
