### ISSUE TITLE
Drawer Elements - Desktop / Mobile

### ISSUE THREAD

**Issue by Timvanderlaan** [bcc-code/bcc-design#228]
## User Story

As a ..., I want to ... so that ...

## Description

...

## Acceptance Criteria:

https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=2767-26965&mode=design

**Comment by laurensgroeneveld** [comment]
These seem to be mostly components in Figma and specific for certain applications, and can be implemented by combining existing components.
