### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by Timvanderlaan** [bcc-code/bcc-design#230]
![image](https://github.com/bcc-code/bcc-design/assets/39056299/59206192-3954-47d0-8a55-b69c3451df89)

## Acceptance Criteria
- The tooltip can be positioned on any side of an element
- A prop can be passed to set the color to one of the three available

## Design

https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=301-2&mode=design

**Comment by lukaspoloki** [comment]
I can take that one, we have it implemented in Budget App
