### ISSUE TITLE
Content Switcher

### ISSUE THREAD

**Issue by Timvanderlaan** [bcc-code/bcc-design#236]
## User Story

As a ..., I want to ... so that ...

## Description

...

## Acceptance Criteria:

https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=2702-25826&mode=design

**Comment by laurensgroeneveld** [comment]
I understand why this is a component in Figma but this seems to be lacking in detail to be able to implement now.
