### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Timvanderlaan** [bcc-code/bcc-design#237]
## User Story

As a ..., I want to ... so that ...

## Description

...

## Acceptance Criteria:

[1.](https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=2933-35092&mode=design)

**Comment by laurensgroeneveld** [comment]
Most of this except the "autocompletion" dropdown was completed in #138

**Comment by laurensgroeneveld** [comment]
I'll combine this issue into #229 for now.
