### ISSUE TITLE
bcc_logo_symbol.svg shouldn't have width and height in the svg

### ISSUE THREAD

**Issue by kklem0** [bcc-code/bcc-design#248]
## Describe the bug
[...](https://github.com/bcc-code/bcc-design/edit/main/www/logos/bcc_logo_symbol.svg)
There's a `width="136" height="136"` in the svg, which makes it hard to auto scale, when I define the width and height to for example 42, it will only show a corner.

## Expected behavior
svg should be without width and height and only have viewBox, so it auto scales.

**Comment by u12206050** [comment]
Can't find any icons that have a static width and height as you mentioned. Closing this issue for now, if you do find one, please state which icon. Thanks

**Comment by kklem0** [comment]
It's in the title.
https://github.com/bcc-code/bcc-design/blob/main/www/logos/bcc_logo_symbol.svg
