### ISSUE TITLE
Nav tabs

### ISSUE THREAD

**Issue by lukaspoloki** [bcc-code/bcc-design#294]
![Screenshot 2024-03-15 at 13 52 59](https://github.com/bcc-code/bcc-design/assets/24432449/0529eb29-a309-434c-9483-7692278c12f8)

![Screenshot 2024-03-15 at 13 53 13](https://github.com/bcc-code/bcc-design/assets/24432449/3cfd9b8a-404a-4d3e-8389-db3f4eca4e9b)

https://www.figma.com/file/6GvZltnPMH3yynzf7287Iu/BCC-Components---Master?type=design&node-id=3302-47571&mode=design&t=sB9WTMs8o5qY5RZA-4

**Comment by lukaspoloki** [comment]
currently implementing in budget app - i can implement it in the component library later

**Comment by laurensgroeneveld** [comment]
@lukaspoloki There is already a BccTabs component: https://design-library.developer.bcc.no/?path=/docs/common-bcctabs--docs

Seems to be the same thing?

**Comment by lukaspoloki** [comment]
Thanks! couldn't find it, I will close this issue 👍🏼
